sonar.projectKey=padmajan87_sample-tracker-resource
sonar.organization=padmajan87-1

# Force SonarCloud to treat files without extensions as Shell scripts
# The double asterisk includes subdirectories
#since we dont have extensions to our shell scripts
sonar.lang.patterns.shell=assets/*, tests/**
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.docker.activate=true
sonar.lang.patterns.docker=Dockerfile
sonar.exclusions=examples/**, tests/**/*.json

