name: Build and publish image to IBM Cloud Container Registry
on:
  release:
    types: [published]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        if: secrets.TOKEN != '' && github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        if: github.event_name == 'release'
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        if: github.event_name == 'release'
        uses: docker/login-action@v1
        with:
            registry: icr.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        if: github.event_name == 'release'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
            build-args: |
              version=${{ github.event.release.tag_name }}
            push: true
            tags: test_sample_tracker
            #test without secrets